# Generated by Django 3.1.7 on 2021-04-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
